//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:gen="http://www.tmforum.org/mtop/fmw/xsd/gen/v1" xmlns:nam="http://www.tmforum.org/mtop/fmw/xsd/nam/v1" xmlns:tns="http://www.tmforum.org/mtop/fmw/xsd/coi/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;The aggregate of all common object attributes.&lt;/p&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for CommonObjectInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonObjectInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.tmforum.org/mtop/fmw/xsd/nam/v1}NamingAttributeType" minOccurs="0"/>
 *         &lt;element name="userLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="discoveredName" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}DiscoveredNameType" minOccurs="0"/>
 *         &lt;element name="namingOs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="owner" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}OwnerType" minOccurs="0"/>
 *         &lt;element name="aliasNameList" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}AliasNameListType" minOccurs="0"/>
 *         &lt;element name="vendorExtensions" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}AnyListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonObjectInfoType", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", propOrder = {
    "name",
    "userLabel",
    "discoveredName",
    "namingOs",
    "owner",
    "aliasNameList",
    "vendorExtensions"
})
@XmlSeeAlso({
    CommonResourceInfoType.class
})
public abstract class CommonObjectInfoType {

    @XmlElementRef(name = "name", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<NamingAttributeType> name;
    @XmlElementRef(name = "userLabel", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> userLabel;
    protected String discoveredName;
    @XmlElementRef(name = "namingOs", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> namingOs;
    @XmlElementRef(name = "owner", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> owner;
    @XmlElementRef(name = "aliasNameList", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<AliasNameListType> aliasNameList;
    @XmlElementRef(name = "vendorExtensions", namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<AnyListType> vendorExtensions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}
     *     
     */
    public JAXBElement<NamingAttributeType> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}
     *     
     */
    public void setName(JAXBElement<NamingAttributeType> value) {
        this.name = value;
    }

    /**
     * Gets the value of the userLabel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUserLabel() {
        return userLabel;
    }

    /**
     * Sets the value of the userLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUserLabel(JAXBElement<String> value) {
        this.userLabel = value;
    }

    /**
     * Gets the value of the discoveredName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscoveredName() {
        return discoveredName;
    }

    /**
     * Sets the value of the discoveredName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscoveredName(String value) {
        this.discoveredName = value;
    }

    /**
     * Gets the value of the namingOs property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNamingOs() {
        return namingOs;
    }

    /**
     * Sets the value of the namingOs property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNamingOs(JAXBElement<String> value) {
        this.namingOs = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOwner(JAXBElement<String> value) {
        this.owner = value;
    }

    /**
     * Gets the value of the aliasNameList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AliasNameListType }{@code >}
     *     
     */
    public JAXBElement<AliasNameListType> getAliasNameList() {
        return aliasNameList;
    }

    /**
     * Sets the value of the aliasNameList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AliasNameListType }{@code >}
     *     
     */
    public void setAliasNameList(JAXBElement<AliasNameListType> value) {
        this.aliasNameList = value;
    }

    /**
     * Gets the value of the vendorExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AnyListType }{@code >}
     *     
     */
    public JAXBElement<AnyListType> getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AnyListType }{@code >}
     *     
     */
    public void setVendorExtensions(JAXBElement<AnyListType> value) {
        this.vendorExtensions = value;
    }

}
