//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:tns="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;The LayerRateType value is used to identify:
 *       &lt;li&gt;the Layer of a PTP/CTP,&lt;/li&gt;&lt;li&gt;the characteristic information of a PTP/FTP,&lt;/li&gt;&lt;li&gt;the Layer/Rate of a connection.&lt;/li&gt;
 * 				&lt;/p&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:tns="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Each LayerRateType may be used in conjunction with a CTP/PTP/FTP of that layer. In the SDH definitions, the G.805 CP and G.805 Termination Function layer names differ, for example TU12 is used for the G.805 CP and VC12 for the corresponding G.805 Termination Function. In this interface definition the TU and VC definitions have been combined into a single composite layer and this has been named to include the equivalent SONET layer, e.g. LR_VT2_andTypeU12_VC12.&lt;/p&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:tns="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;For more details refer to the following supporting document:
 *       &lt;li&gt;layering documentfor all layering concepts&lt;/li&gt;&lt;li&gt;LayerRates document for information about recognized values in MTOSI&lt;/li&gt;
 * 				&lt;/p&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:tns="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;All extensions are permitted (VENDOR_EXT and MINOR_EXT).&lt;/p&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for LayerRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayerRateType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.tmforum.org/mtop/nrb/xsd/lay/v1>LayerRateEnumType">
 *       &lt;attribute name="extension" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayerRateType", namespace = "http://www.tmforum.org/mtop/nrb/xsd/lay/v1", propOrder = {
    "value"
})
public class LayerRateType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "extension")
    protected String extension;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

}
