//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M3100.HolderStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="M3100.HolderStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HOLDER_EMPTY"/>
 *     &lt;enumeration value="INTypeHE_ACCEPTABLE_LIST"/>
 *     &lt;enumeration value="NOT_INTypeHE_ACCEPTABLE_LIST"/>
 *     &lt;enumeration value="UNKNOWNTypeYPE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "M3100.HolderStatusType", namespace = "http://www.tmforum.org/mtop/nrb/xsd/itu/v1")
@XmlEnum
public enum M3100HolderStatusType {

    HOLDER_EMPTY("HOLDER_EMPTY"),
    @XmlEnumValue("INTypeHE_ACCEPTABLE_LIST")
    IN_TYPE_HE_ACCEPTABLE_LIST("INTypeHE_ACCEPTABLE_LIST"),
    @XmlEnumValue("NOT_INTypeHE_ACCEPTABLE_LIST")
    NOT_IN_TYPE_HE_ACCEPTABLE_LIST("NOT_INTypeHE_ACCEPTABLE_LIST"),
    @XmlEnumValue("UNKNOWNTypeYPE")
    UNKNOWN_TYPE_YPE("UNKNOWNTypeYPE");
    private final String value;

    M3100HolderStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static M3100HolderStatusType fromValue(String v) {
        for (M3100HolderStatusType c: M3100HolderStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
