//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for M3100.ArcStateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="M3100.ArcStateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALM"/>
 *     &lt;enumeration value="NALM"/>
 *     &lt;enumeration value="NALMTypeIMED_INHIBIT"/>
 *     &lt;enumeration value="NALM_QUALIFIED_INHIBIT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "M3100.ArcStateType", namespace = "http://www.tmforum.org/mtop/nra/xsd/ituArc/v1")
@XmlEnum
public enum M3100ArcStateType {

    ALM("ALM"),
    NALM("NALM"),
    @XmlEnumValue("NALMTypeIMED_INHIBIT")
    NALM_TYPE_IMED_INHIBIT("NALMTypeIMED_INHIBIT"),
    NALM_QUALIFIED_INHIBIT("NALM_QUALIFIED_INHIBIT");
    private final String value;

    M3100ArcStateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static M3100ArcStateType fromValue(String v) {
        for (M3100ArcStateType c: M3100ArcStateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
