//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObjectEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AID"/>
 *     &lt;enumeration value="ASA"/>
 *     &lt;enumeration value="ASAP"/>
 *     &lt;enumeration value="CTP"/>
 *     &lt;enumeration value="EH"/>
 *     &lt;enumeration value="EPG"/>
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="FDFR"/>
 *     &lt;enumeration value="FTP"/>
 *     &lt;enumeration value="GTP"/>
 *     &lt;enumeration value="MD"/>
 *     &lt;enumeration value="ME"/>
 *     &lt;enumeration value="MFD"/>
 *     &lt;enumeration value="MLSN"/>
 *     &lt;enumeration value="OS"/>
 *     &lt;enumeration value="PG"/>
 *     &lt;enumeration value="PMP"/>
 *     &lt;enumeration value="PTP"/>
 *     &lt;enumeration value="SNC"/>
 *     &lt;enumeration value="TCPROFILE"/>
 *     &lt;enumeration value="TCAPP"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TMD"/>
 *     &lt;enumeration value="TPPOOL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ObjectEnumType", namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1")
@XmlEnum
public enum ObjectEnumType {


    /**
     * Alarm IDentifier (NRA)
     * 
     */
    AID,

    /**
     * Alarm Severity Assignment (NRA)
     * 
     */
    ASA,

    /**
     * Alarm Severity Assignment Profile (NRA)
     * 
     */
    ASAP,

    /**
     * Connection Termination Point (NRF)
     * 
     */
    CTP,

    /**
     * Equipment Holder (NRF)
     * 
     */
    EH,

    /**
     * Equipment Protection Group (NRF)
     * 
     */
    EPG,

    /**
     * Equipment (NRF)
     * 
     */
    EQ,

    /**
     * Flow Domain (NRF)
     * 
     */
    FD,

    /**
     * Flow Domain Fragment (NRF)
     * 
     */
    FDFR,

    /**
     * Flow Termination Point (NRF)
     * 
     */
    FTP,

    /**
     * Group Termination Point (NRF)
     * 
     */
    GTP,

    /**
     * Management Domain (NRF)
     * 
     */
    MD,

    /**
     * Managed Element (NRF)
     * 
     */
    ME,

    /**
     * Matrix Flow Domain (NRF)
     * 
     */
    MFD,

    /**
     * Multi Layer Subnetwork (NRF)
     * 
     */
    MLSN,

    /**
     * Operations System (NRF)
     * 
     */
    OS,

    /**
     * Protection Group (NRF)
     * 
     */
    PG,

    /**
     * Performance Monitoring Point (NRA)
     * 
     */
    PMP,

    /**
     * Physical Termination Point (NRF)
     * 
     */
    PTP,

    /**
     * Subnetwork Connection (NRF)
     * 
     */
    SNC,

    /**
     * Traffic Condifitioning Profile (NRF)
     * 
     */
    TCPROFILE,

    /**
     * Threshold Crossing Alert Parameter Profile (NRF)
     * 
     */
    TCAPP,

    /**
     * Topological Link (NRF)
     * 
     */
    TL,

    /**
     * Transmission Descriptor (NRF)
     * 
     */
    TMD,

    /**
     * Termination Point Pool (NRF)
     * 
     */
    TPPOOL;

    public String value() {
        return name();
    }

    public static ObjectEnumType fromValue(String v) {
        return valueOf(v);
    }

}
