//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 08:15:46 PM IST 
//


package com.lte.discovery.reconciliation.adapter.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:cri="http://www.tmforum.org/mtop/nrb/xsd/cri/v1" xmlns:gen="http://www.tmforum.org/mtop/fmw/xsd/gen/v1" xmlns:me="http://www.tmforum.org/mtop/nrf/xsd/me/v1" xmlns:msg="http://www.tmforum.org/mtop/fmw/xsd/msg/v1" xmlns:nam="http://www.tmforum.org/mtop/fmw/xsd/nam/v1" xmlns:rparams="http://www.example.org/RequestDataType" xmlns:tns="http://www.tmforum.org/mtop/mri/xsd/mer/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Response message structure for a single ManagedElement object&lt;/p&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for SingleMeObjectResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleMeObjectResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="me" type="{http://www.tmforum.org/mtop/nrf/xsd/me/v1}ManagedElementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleMeObjectResponseType", propOrder = {
    "me"
})
public class SingleMeObjectResponseType {

    protected ManagedElementType me;

    /**
     * Gets the value of the me property.
     * 
     * @return
     *     possible object is
     *     {@link ManagedElementType }
     *     
     */
    public ManagedElementType getMe() {
        return me;
    }

    /**
     * Sets the value of the me property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagedElementType }
     *     
     */
    public void setMe(ManagedElementType value) {
        this.me = value;
    }

}
