//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:27:13 PM IST 
//


package com.lte.discovery.reconciliation.management.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:coi="http://www.tmforum.org/mtop/fmw/xsd/coi/v1" xmlns:tns="http://www.tmforum.org/mtop/fmw/xsd/md/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;This aggregate defines the Management Domain mTOP network resource object attributes.&lt;/p&gt;
 * </pre>
 * 
 *       
 * 
 * 
 *             
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:coi="http://www.tmforum.org/mtop/fmw/xsd/coi/v1" xmlns:tns="http://www.tmforum.org/mtop/fmw/xsd/md/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;This element entails the attributes common to all mTOP network resource objects.&lt;/p&gt;
 * </pre>
 * 
 *           
 * 
 * <p>Java class for ManagementDomainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManagementDomainType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tmforum.org/mtop/fmw/xsd/coi/v1}CommonObjectInfoType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManagementDomainType", namespace = "http://www.tmforum.org/mtop/fmw/xsd/md/v1")
public class ManagementDomainType
    extends CommonObjectInfoType
{


}
