//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:27:13 PM IST 
//


package com.lte.discovery.reconciliation.management.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lte.discovery.reconciliation.managementdomain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvalidInput_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidInput");
    private final static QName _InvalidTopic_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidTopic");
    private final static QName _TimeslotInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "timeslotInUse");
    private final static QName _UnableToComply_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unableToComply");
    private final static QName _TooManyOpenIterators_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "tooManyOpenIterators");
    private final static QName _UnsupportedCompressionFormat_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedCompressionFormat");
    private final static QName _NotImplemented_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notImplemented");
    private final static QName _NotificationServiceProblem_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notificationServiceProblem");
    private final static QName _TpInvalidEndPoint_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "tpInvalidEndPoint");
    private final static QName _UserlabelInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "userlabelInUse");
    private final static QName _Md_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/md/v1", "md");
    private final static QName _AccessDenied_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "accessDenied");
    private final static QName _NvsList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "nvsList");
    private final static QName _CommonObjectInfo_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "commonObjectInfo");
    private final static QName _CapacityExceeded_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "capacityExceeded");
    private final static QName _ObjectInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "objectInUse");
    private final static QName _ProtectionEffortNotMet_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "protectionEffortNotMet");
    private final static QName _UnsupportedPackingFormat_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedPackingFormat");
    private final static QName _CommLoss_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "commLoss");
    private final static QName _GetAllManagementDomainsResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mdr/v1", "getAllManagementDomainsResponse");
    private final static QName _InvalidFilterDefinition_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidFilterDefinition");
    private final static QName _InternalError_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "internalError");
    private final static QName _NvList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "nvList");
    private final static QName _GetManagementDomainResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mdr/v1", "getManagementDomainResponse");
    private final static QName _NotInValidState_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notInValidState");
    private final static QName _UnsupportedRoutingConstraints_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedRoutingConstraints");
    private final static QName _EntityNotFound_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "entityNotFound");
    private final static QName _MultiEventInventoryAttributesTypeNeTime_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "neTime");
    private final static QName _CommonObjectInfoTypeNamingOs_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "namingOs");
    private final static QName _CommonObjectInfoTypeUserLabel_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "userLabel");
    private final static QName _CommonObjectInfoTypeAliasNameList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "aliasNameList");
    private final static QName _CommonObjectInfoTypeOwner_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "owner");
    private final static QName _CommonObjectInfoTypeName_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "name");
    private final static QName _CommonObjectInfoTypeVendorExtensions_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "vendorExtensions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lte.discovery.reconciliation.managementdomain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link AliasNameListType }
     * 
     */
    public AliasNameListType createAliasNameListType() {
        return new AliasNameListType();
    }

    /**
     * Create an instance of {@link Header.MsgSpecificProperties }
     * 
     */
    public Header.MsgSpecificProperties createHeaderMsgSpecificProperties() {
        return new Header.MsgSpecificProperties();
    }

    /**
     * Create an instance of {@link GetAllManagementDomainsRequest }
     * 
     */
    public GetAllManagementDomainsRequest createGetAllManagementDomainsRequest() {
        return new GetAllManagementDomainsRequest();
    }

    /**
     * Create an instance of {@link MultipleObjectsResponseType }
     * 
     */
    public MultipleObjectsResponseType createMultipleObjectsResponseType() {
        return new MultipleObjectsResponseType();
    }

    /**
     * Create an instance of {@link GetManagementDomainRequest }
     * 
     */
    public GetManagementDomainRequest createGetManagementDomainRequest() {
        return new GetManagementDomainRequest();
    }

    /**
     * Create an instance of {@link NamingAttributeType }
     * 
     */
    public NamingAttributeType createNamingAttributeType() {
        return new NamingAttributeType();
    }

    /**
     * Create an instance of {@link SingeObjectResponseType }
     * 
     */
    public SingeObjectResponseType createSingeObjectResponseType() {
        return new SingeObjectResponseType();
    }

    /**
     * Create an instance of {@link GetAllManagementDomainsException }
     * 
     */
    public GetAllManagementDomainsException createGetAllManagementDomainsException() {
        return new GetAllManagementDomainsException();
    }

    /**
     * Create an instance of {@link AllExceptionsType }
     * 
     */
    public AllExceptionsType createAllExceptionsType() {
        return new AllExceptionsType();
    }

    /**
     * Create an instance of {@link BaseExceptionMessageType }
     * 
     */
    public BaseExceptionMessageType createBaseExceptionMessageType() {
        return new BaseExceptionMessageType();
    }

    /**
     * Create an instance of {@link GetManagementDomainException }
     * 
     */
    public GetManagementDomainException createGetManagementDomainException() {
        return new GetManagementDomainException();
    }

    /**
     * Create an instance of {@link GetAllDataIteratorRequestType }
     * 
     */
    public GetAllDataIteratorRequestType createGetAllDataIteratorRequestType() {
        return new GetAllDataIteratorRequestType();
    }

    /**
     * Create an instance of {@link GetAllDataIteratorExceptionType }
     * 
     */
    public GetAllDataIteratorExceptionType createGetAllDataIteratorExceptionType() {
        return new GetAllDataIteratorExceptionType();
    }

    /**
     * Create an instance of {@link ActivityStatusType }
     * 
     */
    public ActivityStatusType createActivityStatusType() {
        return new ActivityStatusType();
    }

    /**
     * Create an instance of {@link CompressionTypeType }
     * 
     */
    public CompressionTypeType createCompressionTypeType() {
        return new CompressionTypeType();
    }

    /**
     * Create an instance of {@link PackingTypeType }
     * 
     */
    public PackingTypeType createPackingTypeType() {
        return new PackingTypeType();
    }

    /**
     * Create an instance of {@link AnyListType }
     * 
     */
    public AnyListType createAnyListType() {
        return new AnyListType();
    }

    /**
     * Create an instance of {@link NameAndAnyValueListType }
     * 
     */
    public NameAndAnyValueListType createNameAndAnyValueListType() {
        return new NameAndAnyValueListType();
    }

    /**
     * Create an instance of {@link NameAndValueStringListType }
     * 
     */
    public NameAndValueStringListType createNameAndValueStringListType() {
        return new NameAndValueStringListType();
    }

    /**
     * Create an instance of {@link MultiEventInventoryAttributesType }
     * 
     */
    public MultiEventInventoryAttributesType createMultiEventInventoryAttributesType() {
        return new MultiEventInventoryAttributesType();
    }

    /**
     * Create an instance of {@link NameAndAnyValueType }
     * 
     */
    public NameAndAnyValueType createNameAndAnyValueType() {
        return new NameAndAnyValueType();
    }

    /**
     * Create an instance of {@link NotificationIdentifierListType }
     * 
     */
    public NotificationIdentifierListType createNotificationIdentifierListType() {
        return new NotificationIdentifierListType();
    }

    /**
     * Create an instance of {@link NameAndStringValueType }
     * 
     */
    public NameAndStringValueType createNameAndStringValueType() {
        return new NameAndStringValueType();
    }

    /**
     * Create an instance of {@link QueryExpressionType }
     * 
     */
    public QueryExpressionType createQueryExpressionType() {
        return new QueryExpressionType();
    }

    /**
     * Create an instance of {@link NamingAttributeListType }
     * 
     */
    public NamingAttributeListType createNamingAttributeListType() {
        return new NamingAttributeListType();
    }

    /**
     * Create an instance of {@link RelativeDistinguishNameType }
     * 
     */
    public RelativeDistinguishNameType createRelativeDistinguishNameType() {
        return new RelativeDistinguishNameType();
    }

    /**
     * Create an instance of {@link ManagementDomainType }
     * 
     */
    public ManagementDomainType createManagementDomainType() {
        return new ManagementDomainType();
    }

    /**
     * Create an instance of {@link ManagementDomainListType }
     * 
     */
    public ManagementDomainListType createManagementDomainListType() {
        return new ManagementDomainListType();
    }

    /**
     * Create an instance of {@link AliasNameListType.Alias }
     * 
     */
    public AliasNameListType.Alias createAliasNameListTypeAlias() {
        return new AliasNameListType.Alias();
    }

    /**
     * Create an instance of {@link Header.MsgSpecificProperties.Property }
     * 
     */
    public Header.MsgSpecificProperties.Property createHeaderMsgSpecificPropertiesProperty() {
        return new Header.MsgSpecificProperties.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidInput")
    public JAXBElement<BaseExceptionMessageType> createInvalidInput(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidInput_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidTopic")
    public JAXBElement<BaseExceptionMessageType> createInvalidTopic(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidTopic_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "timeslotInUse")
    public JAXBElement<BaseExceptionMessageType> createTimeslotInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TimeslotInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unableToComply")
    public JAXBElement<BaseExceptionMessageType> createUnableToComply(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnableToComply_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "tooManyOpenIterators")
    public JAXBElement<BaseExceptionMessageType> createTooManyOpenIterators(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TooManyOpenIterators_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedCompressionFormat")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedCompressionFormat(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedCompressionFormat_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notImplemented")
    public JAXBElement<BaseExceptionMessageType> createNotImplemented(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotImplemented_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notificationServiceProblem")
    public JAXBElement<BaseExceptionMessageType> createNotificationServiceProblem(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotificationServiceProblem_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "tpInvalidEndPoint")
    public JAXBElement<BaseExceptionMessageType> createTpInvalidEndPoint(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TpInvalidEndPoint_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "userlabelInUse")
    public JAXBElement<BaseExceptionMessageType> createUserlabelInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UserlabelInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagementDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/md/v1", name = "md")
    public JAXBElement<ManagementDomainType> createMd(ManagementDomainType value) {
        return new JAXBElement<ManagementDomainType>(_Md_QNAME, ManagementDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "accessDenied")
    public JAXBElement<BaseExceptionMessageType> createAccessDenied(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_AccessDenied_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndValueStringListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "nvsList")
    public JAXBElement<NameAndValueStringListType> createNvsList(NameAndValueStringListType value) {
        return new JAXBElement<NameAndValueStringListType>(_NvsList_QNAME, NameAndValueStringListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonObjectInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "commonObjectInfo")
    public JAXBElement<CommonObjectInfoType> createCommonObjectInfo(CommonObjectInfoType value) {
        return new JAXBElement<CommonObjectInfoType>(_CommonObjectInfo_QNAME, CommonObjectInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "capacityExceeded")
    public JAXBElement<BaseExceptionMessageType> createCapacityExceeded(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_CapacityExceeded_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "objectInUse")
    public JAXBElement<BaseExceptionMessageType> createObjectInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_ObjectInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "protectionEffortNotMet")
    public JAXBElement<BaseExceptionMessageType> createProtectionEffortNotMet(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_ProtectionEffortNotMet_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedPackingFormat")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedPackingFormat(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedPackingFormat_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "commLoss")
    public JAXBElement<BaseExceptionMessageType> createCommLoss(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_CommLoss_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleObjectsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mdr/v1", name = "getAllManagementDomainsResponse")
    public JAXBElement<MultipleObjectsResponseType> createGetAllManagementDomainsResponse(MultipleObjectsResponseType value) {
        return new JAXBElement<MultipleObjectsResponseType>(_GetAllManagementDomainsResponse_QNAME, MultipleObjectsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidFilterDefinition")
    public JAXBElement<BaseExceptionMessageType> createInvalidFilterDefinition(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidFilterDefinition_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "internalError")
    public JAXBElement<BaseExceptionMessageType> createInternalError(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InternalError_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndAnyValueListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "nvList")
    public JAXBElement<NameAndAnyValueListType> createNvList(NameAndAnyValueListType value) {
        return new JAXBElement<NameAndAnyValueListType>(_NvList_QNAME, NameAndAnyValueListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingeObjectResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mdr/v1", name = "getManagementDomainResponse")
    public JAXBElement<SingeObjectResponseType> createGetManagementDomainResponse(SingeObjectResponseType value) {
        return new JAXBElement<SingeObjectResponseType>(_GetManagementDomainResponse_QNAME, SingeObjectResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notInValidState")
    public JAXBElement<BaseExceptionMessageType> createNotInValidState(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotInValidState_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedRoutingConstraints")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedRoutingConstraints(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedRoutingConstraints_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "entityNotFound")
    public JAXBElement<BaseExceptionMessageType> createEntityNotFound(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_EntityNotFound_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "neTime", scope = MultiEventInventoryAttributesType.class)
    public JAXBElement<XMLGregorianCalendar> createMultiEventInventoryAttributesTypeNeTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MultiEventInventoryAttributesTypeNeTime_QNAME, XMLGregorianCalendar.class, MultiEventInventoryAttributesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "namingOs", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeNamingOs(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeNamingOs_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "userLabel", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeUserLabel(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeUserLabel_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AliasNameListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "aliasNameList", scope = CommonObjectInfoType.class)
    public JAXBElement<AliasNameListType> createCommonObjectInfoTypeAliasNameList(AliasNameListType value) {
        return new JAXBElement<AliasNameListType>(_CommonObjectInfoTypeAliasNameList_QNAME, AliasNameListType.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "owner", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeOwner(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeOwner_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "name", scope = CommonObjectInfoType.class)
    public JAXBElement<NamingAttributeType> createCommonObjectInfoTypeName(NamingAttributeType value) {
        return new JAXBElement<NamingAttributeType>(_CommonObjectInfoTypeName_QNAME, NamingAttributeType.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "vendorExtensions", scope = CommonObjectInfoType.class)
    public JAXBElement<AnyListType> createCommonObjectInfoTypeVendorExtensions(AnyListType value) {
        return new JAXBElement<AnyListType>(_CommonObjectInfoTypeVendorExtensions_QNAME, AnyListType.class, CommonObjectInfoType.class, value);
    }

}
