//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:27:13 PM IST 
//


package com.lte.discovery.reconciliation.management.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:md="http://www.tmforum.org/mtop/fmw/xsd/md/v1" xmlns:msg="http://www.tmforum.org/mtop/fmw/xsd/msg/v1" xmlns:nam="http://www.tmforum.org/mtop/fmw/xsd/nam/v1" xmlns:tns="http://www.tmforum.org/mtop/mri/xsd/mdr/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Response message structure for one object&lt;/p&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for SingeObjectResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingeObjectResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="md" type="{http://www.tmforum.org/mtop/fmw/xsd/md/v1}ManagementDomainType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingeObjectResponseType", namespace = "http://www.tmforum.org/mtop/mri/xsd/mdr/v1", propOrder = {
    "md"
})
public class SingeObjectResponseType {

    protected ManagementDomainType md;

    /**
     * Gets the value of the md property.
     * 
     * @return
     *     possible object is
     *     {@link ManagementDomainType }
     *     
     */
    public ManagementDomainType getMd() {
        return md;
    }

    /**
     * Sets the value of the md property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagementDomainType }
     *     
     */
    public void setMd(ManagementDomainType value) {
        this.md = value;
    }

}
