//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 12:49:03 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msgName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msgType" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}MessageTypeType" minOccurs="0"/>
 *         &lt;element name="senderURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="destinationURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="replyToURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="originatorURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="failureReplytoURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="activityStatus" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}ActivityStatusType" minOccurs="0"/>
 *         &lt;element name="correlationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="securityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priority" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msgSpecificProperties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="propName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="propValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="communicationPattern" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}CommunicationPatternType" minOccurs="0"/>
 *         &lt;element name="communicationStyle" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}CommunicationStyleType" minOccurs="0"/>
 *         &lt;element name="requestedBatchSize" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="batchSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="batchSequenceEndOfReply" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="iteratorReferenceURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="fileLocationURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="compressionType" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}CompressionTypeType" minOccurs="0"/>
 *         &lt;element name="packingType" type="{http://www.tmforum.org/mtop/fmw/xsd/hdr/v1}PackingTypeType" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="vendorExtensions" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}AnyListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activityName",
    "msgName",
    "msgType",
    "senderURI",
    "destinationURI",
    "replyToURI",
    "originatorURI",
    "failureReplytoURI",
    "activityStatus",
    "correlationId",
    "security",
    "securityType",
    "priority",
    "msgSpecificProperties",
    "communicationPattern",
    "communicationStyle",
    "requestedBatchSize",
    "batchSequenceNumber",
    "batchSequenceEndOfReply",
    "iteratorReferenceURI",
    "fileLocationURI",
    "compressionType",
    "packingType",
    "timestamp",
    "vendorExtensions"
})
@XmlRootElement(name = "header", namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
public class Header {

    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String activityName;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String msgName;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected MessageTypeType msgType;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String senderURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String destinationURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String replyToURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String originatorURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String failureReplytoURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected ActivityStatusType activityStatus;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String correlationId;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String security;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String securityType;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected String priority;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected Header.MsgSpecificProperties msgSpecificProperties;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected CommunicationPatternType communicationPattern;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected CommunicationStyleType communicationStyle;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "unsignedInt")
    protected Long requestedBatchSize;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "unsignedInt")
    protected Long batchSequenceNumber;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected Boolean batchSequenceEndOfReply;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String iteratorReferenceURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "anyURI")
    protected String fileLocationURI;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected CompressionTypeType compressionType;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected PackingTypeType packingType;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
    protected AnyListType vendorExtensions;

    /**
     * Gets the value of the activityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * Sets the value of the activityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityName(String value) {
        this.activityName = value;
    }

    /**
     * Gets the value of the msgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgName() {
        return msgName;
    }

    /**
     * Sets the value of the msgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgName(String value) {
        this.msgName = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link MessageTypeType }
     *     
     */
    public MessageTypeType getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageTypeType }
     *     
     */
    public void setMsgType(MessageTypeType value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the senderURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderURI() {
        return senderURI;
    }

    /**
     * Sets the value of the senderURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderURI(String value) {
        this.senderURI = value;
    }

    /**
     * Gets the value of the destinationURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationURI() {
        return destinationURI;
    }

    /**
     * Sets the value of the destinationURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationURI(String value) {
        this.destinationURI = value;
    }

    /**
     * Gets the value of the replyToURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyToURI() {
        return replyToURI;
    }

    /**
     * Sets the value of the replyToURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyToURI(String value) {
        this.replyToURI = value;
    }

    /**
     * Gets the value of the originatorURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorURI() {
        return originatorURI;
    }

    /**
     * Sets the value of the originatorURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorURI(String value) {
        this.originatorURI = value;
    }

    /**
     * Gets the value of the failureReplytoURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureReplytoURI() {
        return failureReplytoURI;
    }

    /**
     * Sets the value of the failureReplytoURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureReplytoURI(String value) {
        this.failureReplytoURI = value;
    }

    /**
     * Gets the value of the activityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityStatusType }
     *     
     */
    public ActivityStatusType getActivityStatus() {
        return activityStatus;
    }

    /**
     * Sets the value of the activityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityStatusType }
     *     
     */
    public void setActivityStatus(ActivityStatusType value) {
        this.activityStatus = value;
    }

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurity(String value) {
        this.security = value;
    }

    /**
     * Gets the value of the securityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityType() {
        return securityType;
    }

    /**
     * Sets the value of the securityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityType(String value) {
        this.securityType = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the msgSpecificProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Header.MsgSpecificProperties }
     *     
     */
    public Header.MsgSpecificProperties getMsgSpecificProperties() {
        return msgSpecificProperties;
    }

    /**
     * Sets the value of the msgSpecificProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header.MsgSpecificProperties }
     *     
     */
    public void setMsgSpecificProperties(Header.MsgSpecificProperties value) {
        this.msgSpecificProperties = value;
    }

    /**
     * Gets the value of the communicationPattern property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationPatternType }
     *     
     */
    public CommunicationPatternType getCommunicationPattern() {
        return communicationPattern;
    }

    /**
     * Sets the value of the communicationPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationPatternType }
     *     
     */
    public void setCommunicationPattern(CommunicationPatternType value) {
        this.communicationPattern = value;
    }

    /**
     * Gets the value of the communicationStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationStyleType }
     *     
     */
    public CommunicationStyleType getCommunicationStyle() {
        return communicationStyle;
    }

    /**
     * Sets the value of the communicationStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationStyleType }
     *     
     */
    public void setCommunicationStyle(CommunicationStyleType value) {
        this.communicationStyle = value;
    }

    /**
     * Gets the value of the requestedBatchSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRequestedBatchSize() {
        return requestedBatchSize;
    }

    /**
     * Sets the value of the requestedBatchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequestedBatchSize(Long value) {
        this.requestedBatchSize = value;
    }

    /**
     * Gets the value of the batchSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBatchSequenceNumber() {
        return batchSequenceNumber;
    }

    /**
     * Sets the value of the batchSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBatchSequenceNumber(Long value) {
        this.batchSequenceNumber = value;
    }

    /**
     * Gets the value of the batchSequenceEndOfReply property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBatchSequenceEndOfReply() {
        return batchSequenceEndOfReply;
    }

    /**
     * Sets the value of the batchSequenceEndOfReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBatchSequenceEndOfReply(Boolean value) {
        this.batchSequenceEndOfReply = value;
    }

    /**
     * Gets the value of the iteratorReferenceURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteratorReferenceURI() {
        return iteratorReferenceURI;
    }

    /**
     * Sets the value of the iteratorReferenceURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteratorReferenceURI(String value) {
        this.iteratorReferenceURI = value;
    }

    /**
     * Gets the value of the fileLocationURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLocationURI() {
        return fileLocationURI;
    }

    /**
     * Sets the value of the fileLocationURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLocationURI(String value) {
        this.fileLocationURI = value;
    }

    /**
     * Gets the value of the compressionType property.
     * 
     * @return
     *     possible object is
     *     {@link CompressionTypeType }
     *     
     */
    public CompressionTypeType getCompressionType() {
        return compressionType;
    }

    /**
     * Sets the value of the compressionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompressionTypeType }
     *     
     */
    public void setCompressionType(CompressionTypeType value) {
        this.compressionType = value;
    }

    /**
     * Gets the value of the packingType property.
     * 
     * @return
     *     possible object is
     *     {@link PackingTypeType }
     *     
     */
    public PackingTypeType getPackingType() {
        return packingType;
    }

    /**
     * Sets the value of the packingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackingTypeType }
     *     
     */
    public void setPackingType(PackingTypeType value) {
        this.packingType = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the vendorExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link AnyListType }
     *     
     */
    public AnyListType getVendorExtensions() {
        return vendorExtensions;
    }

    /**
     * Sets the value of the vendorExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyListType }
     *     
     */
    public void setVendorExtensions(AnyListType value) {
        this.vendorExtensions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="propName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="propValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class MsgSpecificProperties {

        @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1")
        protected List<Header.MsgSpecificProperties.Property> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Header.MsgSpecificProperties.Property }
         * 
         * 
         */
        public List<Header.MsgSpecificProperties.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<Header.MsgSpecificProperties.Property>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="propName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="propValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "propName",
            "propValue"
        })
        public static class Property {

            @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", required = true)
            protected String propName;
            @XmlElement(namespace = "http://www.tmforum.org/mtop/fmw/xsd/hdr/v1", required = true)
            protected String propValue;

            /**
             * Gets the value of the propName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPropName() {
                return propName;
            }

            /**
             * Sets the value of the propName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPropName(String value) {
                this.propName = value;
            }

            /**
             * Gets the value of the propValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPropValue() {
                return propValue;
            }

            /**
             * Sets the value of the propValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPropValue(String value) {
                this.propValue = value;
            }

        }

    }

}
