//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:40:57 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Containment of all ITU-T Alarm Reporting Control (ARC) state or status parameters supported in mTOP;
 * 			Each element of the list identifies a state or status and provides its relevant value.
 * 			
 * 
 * <p>Java class for ItuArcStateAndStatusList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItuArcStateAndStatusList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m3100.AlarmStatus" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.AlarmStatusType" minOccurs="0"/>
 *         &lt;element name="m3100.ArcState" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.ArcStateType" minOccurs="0"/>
 *         &lt;element name="m3100.NALMTIInterval" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.NALMTIIntervalType" minOccurs="0"/>
 *         &lt;element name="m3100.NALMQIInterval" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.NALMQIIntervalType" minOccurs="0"/>
 *         &lt;element name="m3100.ArcQIStatus" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.ArcQIStatusType" minOccurs="0"/>
 *         &lt;element name="m3100.State" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.ArcStateListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItuArcStateAndStatusList", namespace = "http://www.tmforum.org/mtop/nra/xsd/ituArc/v1", propOrder = {
    "m3100AlarmStatus",
    "m3100ArcState",
    "m3100NALMTIInterval",
    "m3100NALMQIInterval",
    "m3100ArcQIStatus",
    "m3100State"
})
public class ItuArcStateAndStatusList {

    @XmlElement(name = "m3100.AlarmStatus")
    protected M3100AlarmStatusType m3100AlarmStatus;
    @XmlElement(name = "m3100.ArcState")
    protected M3100ArcStateType m3100ArcState;
    @XmlElement(name = "m3100.NALMTIInterval")
    protected String m3100NALMTIInterval;
    @XmlElement(name = "m3100.NALMQIInterval")
    protected String m3100NALMQIInterval;
    @XmlElement(name = "m3100.ArcQIStatus")
    protected M3100ArcQIStatusType m3100ArcQIStatus;
    @XmlElement(name = "m3100.State")
    protected M3100ArcStateListType m3100State;

    /**
     * Gets the value of the m3100AlarmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100AlarmStatusType }
     *     
     */
    public M3100AlarmStatusType getM3100AlarmStatus() {
        return m3100AlarmStatus;
    }

    /**
     * Sets the value of the m3100AlarmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100AlarmStatusType }
     *     
     */
    public void setM3100AlarmStatus(M3100AlarmStatusType value) {
        this.m3100AlarmStatus = value;
    }

    /**
     * Gets the value of the m3100ArcState property.
     * 
     * @return
     *     possible object is
     *     {@link M3100ArcStateType }
     *     
     */
    public M3100ArcStateType getM3100ArcState() {
        return m3100ArcState;
    }

    /**
     * Sets the value of the m3100ArcState property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100ArcStateType }
     *     
     */
    public void setM3100ArcState(M3100ArcStateType value) {
        this.m3100ArcState = value;
    }

    /**
     * Gets the value of the m3100NALMTIInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM3100NALMTIInterval() {
        return m3100NALMTIInterval;
    }

    /**
     * Sets the value of the m3100NALMTIInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM3100NALMTIInterval(String value) {
        this.m3100NALMTIInterval = value;
    }

    /**
     * Gets the value of the m3100NALMQIInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM3100NALMQIInterval() {
        return m3100NALMQIInterval;
    }

    /**
     * Sets the value of the m3100NALMQIInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM3100NALMQIInterval(String value) {
        this.m3100NALMQIInterval = value;
    }

    /**
     * Gets the value of the m3100ArcQIStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100ArcQIStatusType }
     *     
     */
    public M3100ArcQIStatusType getM3100ArcQIStatus() {
        return m3100ArcQIStatus;
    }

    /**
     * Sets the value of the m3100ArcQIStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100ArcQIStatusType }
     *     
     */
    public void setM3100ArcQIStatus(M3100ArcQIStatusType value) {
        this.m3100ArcQIStatus = value;
    }

    /**
     * Gets the value of the m3100State property.
     * 
     * @return
     *     possible object is
     *     {@link M3100ArcStateListType }
     *     
     */
    public M3100ArcStateListType getM3100State() {
        return m3100State;
    }

    /**
     * Sets the value of the m3100State property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100ArcStateListType }
     *     
     */
    public void setM3100State(M3100ArcStateListType value) {
        this.m3100State = value;
    }

}
