//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:40:57 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Containment of all ITU-T state or status parameters supported in mTOP
 * 
 * <p>Java class for ItuStateAndStatusList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItuStateAndStatusList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x721.OperationalState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.OperationalStateType" minOccurs="0"/>
 *         &lt;element name="x721.AdministrativeState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.AdministrativeStateType" minOccurs="0"/>
 *         &lt;element name="x721.UsageState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.UsageStateType" minOccurs="0"/>
 *         &lt;element name="x721.AvailabilityStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.AvailabilityStatusType" minOccurs="0"/>
 *         &lt;element name="x721.ControlStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.ControlStatusType" minOccurs="0"/>
 *         &lt;element name="m3100.HolderStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}M3100.HolderStatusType" minOccurs="0"/>
 *         &lt;element name="m3100.CircuitPackType" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}M3100.CircuitPackTypeType" minOccurs="0"/>
 *         &lt;element name="x721.Unkownstatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.UnkownstatusType" minOccurs="0"/>
 *         &lt;element name="x721.State" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.StateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItuStateAndStatusList", namespace = "http://www.tmforum.org/mtop/nrb/xsd/itu/v1", propOrder = {
    "x721OperationalState",
    "x721AdministrativeState",
    "x721UsageState",
    "x721AvailabilityStatus",
    "x721ControlStatus",
    "m3100HolderStatus",
    "m3100CircuitPackType",
    "x721Unkownstatus",
    "x721State"
})
public class ItuStateAndStatusList {

    @XmlElement(name = "x721.OperationalState")
    protected X721OperationalStateType x721OperationalState;
    @XmlElement(name = "x721.AdministrativeState")
    protected X721AdministrativeStateType x721AdministrativeState;
    @XmlElement(name = "x721.UsageState")
    protected X721UsageStateType x721UsageState;
    @XmlElement(name = "x721.AvailabilityStatus")
    protected String x721AvailabilityStatus;
    @XmlElement(name = "x721.ControlStatus")
    protected String x721ControlStatus;
    @XmlElement(name = "m3100.HolderStatus")
    protected M3100HolderStatusType m3100HolderStatus;
    @XmlElement(name = "m3100.CircuitPackType")
    protected String m3100CircuitPackType;
    @XmlElement(name = "x721.Unkownstatus")
    protected Boolean x721Unkownstatus;
    @XmlElement(name = "x721.State")
    protected X721StateType x721State;

    /**
     * Gets the value of the x721OperationalState property.
     * 
     * @return
     *     possible object is
     *     {@link X721OperationalStateType }
     *     
     */
    public X721OperationalStateType getX721OperationalState() {
        return x721OperationalState;
    }

    /**
     * Sets the value of the x721OperationalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721OperationalStateType }
     *     
     */
    public void setX721OperationalState(X721OperationalStateType value) {
        this.x721OperationalState = value;
    }

    /**
     * Gets the value of the x721AdministrativeState property.
     * 
     * @return
     *     possible object is
     *     {@link X721AdministrativeStateType }
     *     
     */
    public X721AdministrativeStateType getX721AdministrativeState() {
        return x721AdministrativeState;
    }

    /**
     * Sets the value of the x721AdministrativeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721AdministrativeStateType }
     *     
     */
    public void setX721AdministrativeState(X721AdministrativeStateType value) {
        this.x721AdministrativeState = value;
    }

    /**
     * Gets the value of the x721UsageState property.
     * 
     * @return
     *     possible object is
     *     {@link X721UsageStateType }
     *     
     */
    public X721UsageStateType getX721UsageState() {
        return x721UsageState;
    }

    /**
     * Sets the value of the x721UsageState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721UsageStateType }
     *     
     */
    public void setX721UsageState(X721UsageStateType value) {
        this.x721UsageState = value;
    }

    /**
     * Gets the value of the x721AvailabilityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX721AvailabilityStatus() {
        return x721AvailabilityStatus;
    }

    /**
     * Sets the value of the x721AvailabilityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX721AvailabilityStatus(String value) {
        this.x721AvailabilityStatus = value;
    }

    /**
     * Gets the value of the x721ControlStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX721ControlStatus() {
        return x721ControlStatus;
    }

    /**
     * Sets the value of the x721ControlStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX721ControlStatus(String value) {
        this.x721ControlStatus = value;
    }

    /**
     * Gets the value of the m3100HolderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100HolderStatusType }
     *     
     */
    public M3100HolderStatusType getM3100HolderStatus() {
        return m3100HolderStatus;
    }

    /**
     * Sets the value of the m3100HolderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100HolderStatusType }
     *     
     */
    public void setM3100HolderStatus(M3100HolderStatusType value) {
        this.m3100HolderStatus = value;
    }

    /**
     * Gets the value of the m3100CircuitPackType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM3100CircuitPackType() {
        return m3100CircuitPackType;
    }

    /**
     * Sets the value of the m3100CircuitPackType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM3100CircuitPackType(String value) {
        this.m3100CircuitPackType = value;
    }

    /**
     * Gets the value of the x721Unkownstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isX721Unkownstatus() {
        return x721Unkownstatus;
    }

    /**
     * Sets the value of the x721Unkownstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setX721Unkownstatus(Boolean value) {
        this.x721Unkownstatus = value;
    }

    /**
     * Gets the value of the x721State property.
     * 
     * @return
     *     possible object is
     *     {@link X721StateType }
     *     
     */
    public X721StateType getX721State() {
        return x721State;
    }

    /**
     * Sets the value of the x721State property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721StateType }
     *     
     */
    public void setX721State(X721StateType value) {
        this.x721State = value;
    }

}
