//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 12:49:03 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * State parameter from ITU-T state or status
 * 
 * <p>Java class for M3100.ArcStateListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="M3100.ArcStateListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="M3100.AlarmStatus" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.AlarmStatusType" minOccurs="0"/>
 *         &lt;element name="M3100.ArcState" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.ArcStateType" minOccurs="0"/>
 *         &lt;element name="M3100.ArcQIStatus" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}M3100.ArcQIStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "M3100.ArcStateListType", namespace = "http://www.tmforum.org/mtop/nra/xsd/ituArc/v1", propOrder = {
    "m3100AlarmStatus",
    "m3100ArcState",
    "m3100ArcQIStatus"
})
public class M3100ArcStateListType {

    @XmlElement(name = "M3100.AlarmStatus")
    protected M3100AlarmStatusType m3100AlarmStatus;
    @XmlElement(name = "M3100.ArcState")
    protected M3100ArcStateType m3100ArcState;
    @XmlElement(name = "M3100.ArcQIStatus")
    protected M3100ArcQIStatusType m3100ArcQIStatus;

    /**
     * Gets the value of the m3100AlarmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100AlarmStatusType }
     *     
     */
    public M3100AlarmStatusType getM3100AlarmStatus() {
        return m3100AlarmStatus;
    }

    /**
     * Sets the value of the m3100AlarmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100AlarmStatusType }
     *     
     */
    public void setM3100AlarmStatus(M3100AlarmStatusType value) {
        this.m3100AlarmStatus = value;
    }

    /**
     * Gets the value of the m3100ArcState property.
     * 
     * @return
     *     possible object is
     *     {@link M3100ArcStateType }
     *     
     */
    public M3100ArcStateType getM3100ArcState() {
        return m3100ArcState;
    }

    /**
     * Sets the value of the m3100ArcState property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100ArcStateType }
     *     
     */
    public void setM3100ArcState(M3100ArcStateType value) {
        this.m3100ArcState = value;
    }

    /**
     * Gets the value of the m3100ArcQIStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100ArcQIStatusType }
     *     
     */
    public M3100ArcQIStatusType getM3100ArcQIStatus() {
        return m3100ArcQIStatus;
    }

    /**
     * Sets the value of the m3100ArcQIStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100ArcQIStatusType }
     *     
     */
    public void setM3100ArcQIStatus(M3100ArcQIStatusType value) {
        this.m3100ArcQIStatus = value;
    }

}
