//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:40:57 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:cri="http://www.tmforum.org/mtop/nrb/xsd/cri/v1" xmlns:gen="http://www.tmforum.org/mtop/fmw/xsd/gen/v1" xmlns:ituArc="http://www.tmforum.org/mtop/nra/xsd/ituArc/v1" xmlns:lay="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:nam="http://www.tmforum.org/mtop/fmw/xsd/nam/v1" xmlns:tns="http://www.tmforum.org/mtop/nrf/xsd/me/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;This aggregate defines all the Managed Element mTOP network resource object attributes.&lt;/p&gt;
 * </pre>
 * 
 * 			
 * 
 * 
 * 						
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:cri="http://www.tmforum.org/mtop/nrb/xsd/cri/v1" xmlns:gen="http://www.tmforum.org/mtop/fmw/xsd/gen/v1" xmlns:ituArc="http://www.tmforum.org/mtop/nra/xsd/ituArc/v1" xmlns:lay="http://www.tmforum.org/mtop/nrb/xsd/lay/v1" xmlns:nam="http://www.tmforum.org/mtop/fmw/xsd/nam/v1" xmlns:tns="http://www.tmforum.org/mtop/nrf/xsd/me/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;This element entails the attributes common to all mTOP network resource objects.&lt;/p&gt;
 * </pre>
 * 
 * 					
 * 
 * <p>Java class for ManagedElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManagedElementType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tmforum.org/mtop/nrb/xsd/cri/v1}CommonResourceInfoType">
 *       &lt;sequence>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="manufactureDate" type="{http://www.tmforum.org/mtop/fmw/xsd/gen/v1}ManufactureDateType" minOccurs="0"/>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="softwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isInSyncState" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="supportedConnectionLayerRateList" type="{http://www.tmforum.org/mtop/nrb/xsd/lay/v1}LayerRateListType" minOccurs="0"/>
 *         &lt;element name="communicationState" type="{http://www.tmforum.org/mtop/nrf/xsd/me/v1}CommunicationStateType" minOccurs="0"/>
 *         &lt;element name="asapRef" type="{http://www.tmforum.org/mtop/fmw/xsd/nam/v1}NamingAttributeType" minOccurs="0"/>
 *         &lt;element name="ituArcStateAndStatusList" type="{http://www.tmforum.org/mtop/nra/xsd/ituArc/v1}ItuArcStateAndStatusList"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManagedElementType", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", propOrder = {
    "location",
    "manufacturer",
    "manufactureDate",
    "productName",
    "softwareVersion",
    "isInSyncState",
    "supportedConnectionLayerRateList",
    "communicationState",
    "asapRef",
    "ituArcStateAndStatusList"
})
public class ManagedElementType
    extends CommonResourceInfoType
{

    @XmlElementRef(name = "location", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> location;
    @XmlElementRef(name = "manufacturer", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> manufacturer;
    @XmlElementRef(name = "manufactureDate", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> manufactureDate;
    @XmlElementRef(name = "productName", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> productName;
    @XmlElementRef(name = "softwareVersion", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> softwareVersion;
    @XmlElementRef(name = "isInSyncState", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> isInSyncState;
    @XmlElementRef(name = "supportedConnectionLayerRateList", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<LayerRateListType> supportedConnectionLayerRateList;
    @XmlElementRef(name = "communicationState", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<CommunicationStateType> communicationState;
    @XmlElementRef(name = "asapRef", namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<NamingAttributeType> asapRef;
    @XmlElement(required = true)
    protected ItuArcStateAndStatusList ituArcStateAndStatusList;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLocation(JAXBElement<String> value) {
        this.location = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setManufacturer(JAXBElement<String> value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the manufactureDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getManufactureDate() {
        return manufactureDate;
    }

    /**
     * Sets the value of the manufactureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setManufactureDate(JAXBElement<XMLGregorianCalendar> value) {
        this.manufactureDate = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProductName(JAXBElement<String> value) {
        this.productName = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSoftwareVersion(JAXBElement<String> value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the isInSyncState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getIsInSyncState() {
        return isInSyncState;
    }

    /**
     * Sets the value of the isInSyncState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setIsInSyncState(JAXBElement<Boolean> value) {
        this.isInSyncState = value;
    }

    /**
     * Gets the value of the supportedConnectionLayerRateList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LayerRateListType }{@code >}
     *     
     */
    public JAXBElement<LayerRateListType> getSupportedConnectionLayerRateList() {
        return supportedConnectionLayerRateList;
    }

    /**
     * Sets the value of the supportedConnectionLayerRateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LayerRateListType }{@code >}
     *     
     */
    public void setSupportedConnectionLayerRateList(JAXBElement<LayerRateListType> value) {
        this.supportedConnectionLayerRateList = value;
    }

    /**
     * Gets the value of the communicationState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CommunicationStateType }{@code >}
     *     
     */
    public JAXBElement<CommunicationStateType> getCommunicationState() {
        return communicationState;
    }

    /**
     * Sets the value of the communicationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CommunicationStateType }{@code >}
     *     
     */
    public void setCommunicationState(JAXBElement<CommunicationStateType> value) {
        this.communicationState = value;
    }

    /**
     * Gets the value of the asapRef property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}
     *     
     */
    public JAXBElement<NamingAttributeType> getAsapRef() {
        return asapRef;
    }

    /**
     * Sets the value of the asapRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}
     *     
     */
    public void setAsapRef(JAXBElement<NamingAttributeType> value) {
        this.asapRef = value;
    }

    /**
     * Gets the value of the ituArcStateAndStatusList property.
     * 
     * @return
     *     possible object is
     *     {@link ItuArcStateAndStatusList }
     *     
     */
    public ItuArcStateAndStatusList getItuArcStateAndStatusList() {
        return ituArcStateAndStatusList;
    }

    /**
     * Sets the value of the ituArcStateAndStatusList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItuArcStateAndStatusList }
     *     
     */
    public void setItuArcStateAndStatusList(ItuArcStateAndStatusList value) {
        this.ituArcStateAndStatusList = value;
    }

}
