//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 12:49:03 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This attribute is used when a object instance is embedded in the inventory
 * 			layout payload of a Multi-Event Inventory (MEI) notification.
 * 
 * <p>Java class for MultiEventInventoryAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiEventInventoryAttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="neTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="eventIndication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiEventInventoryAttributesType", namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", propOrder = {
    "neTime",
    "eventIndication"
})
public class MultiEventInventoryAttributesType {

    @XmlElementRef(name = "neTime", namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> neTime;
    @XmlElement(required = true)
    protected String eventIndication;

    /**
     * Gets the value of the neTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getNeTime() {
        return neTime;
    }

    /**
     * Sets the value of the neTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setNeTime(JAXBElement<XMLGregorianCalendar> value) {
        this.neTime = value;
    }

    /**
     * Gets the value of the eventIndication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventIndication() {
        return eventIndication;
    }

    /**
     * Sets the value of the eventIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventIndication(String value) {
        this.eventIndication = value;
    }

}
