//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.01 at 12:49:03 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lte.discovery.reconciliation.managed.element package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvalidInput_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidInput");
    private final static QName _GetAllManagedElementsResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getAllManagedElementsResponse");
    private final static QName _InvalidTopic_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidTopic");
    private final static QName _TimeslotInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "timeslotInUse");
    private final static QName _UnableToComply_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unableToComply");
    private final static QName _TooManyOpenIterators_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "tooManyOpenIterators");
    private final static QName _UnsupportedCompressionFormat_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedCompressionFormat");
    private final static QName _NotImplemented_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notImplemented");
    private final static QName _NotificationServiceProblem_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notificationServiceProblem");
    private final static QName _TpInvalidEndPoint_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "tpInvalidEndPoint");
    private final static QName _GetManagedElementResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getManagedElementResponse");
    private final static QName _UserlabelInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "userlabelInUse");
    private final static QName _AccessDenied_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "accessDenied");
    private final static QName _GetManagedElementsIteratorException_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getManagedElementsIteratorException");
    private final static QName _CommonResourceInfo_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/cri/v1", "commonResourceInfo");
    private final static QName _NvsList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "nvsList");
    private final static QName _GetAllManagedElementsWrtOsResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getAllManagedElementsWrtOsResponse");
    private final static QName _CommonObjectInfo_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "commonObjectInfo");
    private final static QName _CapacityExceeded_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "capacityExceeded");
    private final static QName _ObjectInUse_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "objectInUse");
    private final static QName _GetManagedElementsIteratorRequest_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getManagedElementsIteratorRequest");
    private final static QName _GetManagedElementsIteratorResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getManagedElementsIteratorResponse");
    private final static QName _LayerRateListType_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/lay/v1", "layerRateListType");
    private final static QName _ProtectionEffortNotMet_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "protectionEffortNotMet");
    private final static QName _UnsupportedPackingFormat_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedPackingFormat");
    private final static QName _Me_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "me");
    private final static QName _CommLoss_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "commLoss");
    private final static QName _InvalidFilterDefinition_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "invalidFilterDefinition");
    private final static QName _NvList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "nvList");
    private final static QName _InternalError_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "internalError");
    private final static QName _NotInValidState_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "notInValidState");
    private final static QName _GetAllManagedElementsPassingFilterResponse_QNAME = new QName("http://www.tmforum.org/mtop/mri/xsd/mer/v1", "getAllManagedElementsPassingFilterResponse");
    private final static QName _UnsupportedRoutingConstraints_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "unsupportedRoutingConstraints");
    private final static QName _EntityNotFound_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/msg/v1", "entityNotFound");
    private final static QName _CommonResourceInfoTypeResourceState_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/cri/v1", "resourceState");
    private final static QName _CommonResourceInfoTypeNetworkAccessDomain_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/cri/v1", "networkAccessDomain");
    private final static QName _CommonResourceInfoTypeMeiAttributes_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/cri/v1", "meiAttributes");
    private final static QName _CommonResourceInfoTypeSource_QNAME = new QName("http://www.tmforum.org/mtop/nrb/xsd/cri/v1", "source");
    private final static QName _CommonObjectInfoTypeNamingOs_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "namingOs");
    private final static QName _CommonObjectInfoTypeUserLabel_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "userLabel");
    private final static QName _CommonObjectInfoTypeAliasNameList_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "aliasNameList");
    private final static QName _CommonObjectInfoTypeOwner_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "owner");
    private final static QName _CommonObjectInfoTypeName_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "name");
    private final static QName _CommonObjectInfoTypeVendorExtensions_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/coi/v1", "vendorExtensions");
    private final static QName _MultiEventInventoryAttributesTypeNeTime_QNAME = new QName("http://www.tmforum.org/mtop/fmw/xsd/gen/v1", "neTime");
    private final static QName _ManagedElementTypeLocation_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "location");
    private final static QName _ManagedElementTypeManufacturer_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "manufacturer");
    private final static QName _ManagedElementTypeSupportedConnectionLayerRateList_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "supportedConnectionLayerRateList");
    private final static QName _ManagedElementTypeAsapRef_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "asapRef");
    private final static QName _ManagedElementTypeCommunicationState_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "communicationState");
    private final static QName _ManagedElementTypeProductName_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "productName");
    private final static QName _ManagedElementTypeIsInSyncState_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "isInSyncState");
    private final static QName _ManagedElementTypeManufactureDate_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "manufactureDate");
    private final static QName _ManagedElementTypeSoftwareVersion_QNAME = new QName("http://www.tmforum.org/mtop/nrf/xsd/me/v1", "softwareVersion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lte.discovery.reconciliation.managed.element
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Header.MsgSpecificProperties }
     * 
     */
    public Header.MsgSpecificProperties createHeaderMsgSpecificProperties() {
        return new Header.MsgSpecificProperties();
    }

    /**
     * Create an instance of {@link AliasNameListType }
     * 
     */
    public AliasNameListType createAliasNameListType() {
        return new AliasNameListType();
    }

    /**
     * Create an instance of {@link GetManagedElementException }
     * 
     */
    public GetManagedElementException createGetManagedElementException() {
        return new GetManagedElementException();
    }

    /**
     * Create an instance of {@link AllExceptionsType }
     * 
     */
    public AllExceptionsType createAllExceptionsType() {
        return new AllExceptionsType();
    }

    /**
     * Create an instance of {@link BaseExceptionMessageType }
     * 
     */
    public BaseExceptionMessageType createBaseExceptionMessageType() {
        return new BaseExceptionMessageType();
    }

    /**
     * Create an instance of {@link MultipleMeObjectsResponseType }
     * 
     */
    public MultipleMeObjectsResponseType createMultipleMeObjectsResponseType() {
        return new MultipleMeObjectsResponseType();
    }

    /**
     * Create an instance of {@link GetAllDataIteratorRequestType }
     * 
     */
    public GetAllDataIteratorRequestType createGetAllDataIteratorRequestType() {
        return new GetAllDataIteratorRequestType();
    }

    /**
     * Create an instance of {@link SingleMeObjectResponseType }
     * 
     */
    public SingleMeObjectResponseType createSingleMeObjectResponseType() {
        return new SingleMeObjectResponseType();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsPassingFilterRequest }
     * 
     */
    public GetAllManagedElementsPassingFilterRequest createGetAllManagedElementsPassingFilterRequest() {
        return new GetAllManagedElementsPassingFilterRequest();
    }

    /**
     * Create an instance of {@link NamingAttributeType }
     * 
     */
    public NamingAttributeType createNamingAttributeType() {
        return new NamingAttributeType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsWrtOsException }
     * 
     */
    public GetAllManagedElementsWrtOsException createGetAllManagedElementsWrtOsException() {
        return new GetAllManagedElementsWrtOsException();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsRequest }
     * 
     */
    public GetAllManagedElementsRequest createGetAllManagedElementsRequest() {
        return new GetAllManagedElementsRequest();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsException }
     * 
     */
    public GetAllManagedElementsException createGetAllManagedElementsException() {
        return new GetAllManagedElementsException();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsWrtOsRequest }
     * 
     */
    public GetAllManagedElementsWrtOsRequest createGetAllManagedElementsWrtOsRequest() {
        return new GetAllManagedElementsWrtOsRequest();
    }

    /**
     * Create an instance of {@link GetManagedElementRequest }
     * 
     */
    public GetManagedElementRequest createGetManagedElementRequest() {
        return new GetManagedElementRequest();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link GetAllManagedElementsPassingFilterException }
     * 
     */
    public GetAllManagedElementsPassingFilterException createGetAllManagedElementsPassingFilterException() {
        return new GetAllManagedElementsPassingFilterException();
    }

    /**
     * Create an instance of {@link GetAllDataIteratorExceptionType }
     * 
     */
    public GetAllDataIteratorExceptionType createGetAllDataIteratorExceptionType() {
        return new GetAllDataIteratorExceptionType();
    }

    /**
     * Create an instance of {@link NameAndAnyValueListType }
     * 
     */
    public NameAndAnyValueListType createNameAndAnyValueListType() {
        return new NameAndAnyValueListType();
    }

    /**
     * Create an instance of {@link NameAndValueStringListType }
     * 
     */
    public NameAndValueStringListType createNameAndValueStringListType() {
        return new NameAndValueStringListType();
    }

    /**
     * Create an instance of {@link MultiEventInventoryAttributesType }
     * 
     */
    public MultiEventInventoryAttributesType createMultiEventInventoryAttributesType() {
        return new MultiEventInventoryAttributesType();
    }

    /**
     * Create an instance of {@link NameAndAnyValueType }
     * 
     */
    public NameAndAnyValueType createNameAndAnyValueType() {
        return new NameAndAnyValueType();
    }

    /**
     * Create an instance of {@link AnyListType }
     * 
     */
    public AnyListType createAnyListType() {
        return new AnyListType();
    }

    /**
     * Create an instance of {@link NotificationIdentifierListType }
     * 
     */
    public NotificationIdentifierListType createNotificationIdentifierListType() {
        return new NotificationIdentifierListType();
    }

    /**
     * Create an instance of {@link NameAndStringValueType }
     * 
     */
    public NameAndStringValueType createNameAndStringValueType() {
        return new NameAndStringValueType();
    }

    /**
     * Create an instance of {@link QueryExpressionType }
     * 
     */
    public QueryExpressionType createQueryExpressionType() {
        return new QueryExpressionType();
    }

    /**
     * Create an instance of {@link ActivityStatusType }
     * 
     */
    public ActivityStatusType createActivityStatusType() {
        return new ActivityStatusType();
    }

    /**
     * Create an instance of {@link CompressionTypeType }
     * 
     */
    public CompressionTypeType createCompressionTypeType() {
        return new CompressionTypeType();
    }

    /**
     * Create an instance of {@link PackingTypeType }
     * 
     */
    public PackingTypeType createPackingTypeType() {
        return new PackingTypeType();
    }

    /**
     * Create an instance of {@link NamingAttributeListType }
     * 
     */
    public NamingAttributeListType createNamingAttributeListType() {
        return new NamingAttributeListType();
    }

    /**
     * Create an instance of {@link RelativeDistinguishNameType }
     * 
     */
    public RelativeDistinguishNameType createRelativeDistinguishNameType() {
        return new RelativeDistinguishNameType();
    }

    /**
     * Create an instance of {@link ResourceStateType }
     * 
     */
    public ResourceStateType createResourceStateType() {
        return new ResourceStateType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link ItuStateAndStatusList }
     * 
     */
    public ItuStateAndStatusList createItuStateAndStatusList() {
        return new ItuStateAndStatusList();
    }

    /**
     * Create an instance of {@link X721StateType }
     * 
     */
    public X721StateType createX721StateType() {
        return new X721StateType();
    }

    /**
     * Create an instance of {@link ManagedElementType }
     * 
     */
    public ManagedElementType createManagedElementType() {
        return new ManagedElementType();
    }

    /**
     * Create an instance of {@link ManagedElementListType }
     * 
     */
    public ManagedElementListType createManagedElementListType() {
        return new ManagedElementListType();
    }

    /**
     * Create an instance of {@link LayerRateListType }
     * 
     */
    public LayerRateListType createLayerRateListType() {
        return new LayerRateListType();
    }

    /**
     * Create an instance of {@link LayerRateType }
     * 
     */
    public LayerRateType createLayerRateType() {
        return new LayerRateType();
    }

    /**
     * Create an instance of {@link ItuArcStateAndStatusList }
     * 
     */
    public ItuArcStateAndStatusList createItuArcStateAndStatusList() {
        return new ItuArcStateAndStatusList();
    }

    /**
     * Create an instance of {@link M3100ArcStateListType }
     * 
     */
    public M3100ArcStateListType createM3100ArcStateListType() {
        return new M3100ArcStateListType();
    }

    /**
     * Create an instance of {@link Header.MsgSpecificProperties.Property }
     * 
     */
    public Header.MsgSpecificProperties.Property createHeaderMsgSpecificPropertiesProperty() {
        return new Header.MsgSpecificProperties.Property();
    }

    /**
     * Create an instance of {@link AliasNameListType.Alias }
     * 
     */
    public AliasNameListType.Alias createAliasNameListTypeAlias() {
        return new AliasNameListType.Alias();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidInput")
    public JAXBElement<BaseExceptionMessageType> createInvalidInput(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidInput_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleMeObjectsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getAllManagedElementsResponse")
    public JAXBElement<MultipleMeObjectsResponseType> createGetAllManagedElementsResponse(MultipleMeObjectsResponseType value) {
        return new JAXBElement<MultipleMeObjectsResponseType>(_GetAllManagedElementsResponse_QNAME, MultipleMeObjectsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidTopic")
    public JAXBElement<BaseExceptionMessageType> createInvalidTopic(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidTopic_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "timeslotInUse")
    public JAXBElement<BaseExceptionMessageType> createTimeslotInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TimeslotInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unableToComply")
    public JAXBElement<BaseExceptionMessageType> createUnableToComply(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnableToComply_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "tooManyOpenIterators")
    public JAXBElement<BaseExceptionMessageType> createTooManyOpenIterators(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TooManyOpenIterators_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedCompressionFormat")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedCompressionFormat(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedCompressionFormat_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notImplemented")
    public JAXBElement<BaseExceptionMessageType> createNotImplemented(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotImplemented_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notificationServiceProblem")
    public JAXBElement<BaseExceptionMessageType> createNotificationServiceProblem(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotificationServiceProblem_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "tpInvalidEndPoint")
    public JAXBElement<BaseExceptionMessageType> createTpInvalidEndPoint(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_TpInvalidEndPoint_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleMeObjectResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getManagedElementResponse")
    public JAXBElement<SingleMeObjectResponseType> createGetManagedElementResponse(SingleMeObjectResponseType value) {
        return new JAXBElement<SingleMeObjectResponseType>(_GetManagedElementResponse_QNAME, SingleMeObjectResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "userlabelInUse")
    public JAXBElement<BaseExceptionMessageType> createUserlabelInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UserlabelInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "accessDenied")
    public JAXBElement<BaseExceptionMessageType> createAccessDenied(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_AccessDenied_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllDataIteratorExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getManagedElementsIteratorException")
    public JAXBElement<GetAllDataIteratorExceptionType> createGetManagedElementsIteratorException(GetAllDataIteratorExceptionType value) {
        return new JAXBElement<GetAllDataIteratorExceptionType>(_GetManagedElementsIteratorException_QNAME, GetAllDataIteratorExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonResourceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1", name = "commonResourceInfo", substitutionHeadNamespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", substitutionHeadName = "commonObjectInfo")
    public JAXBElement<CommonResourceInfoType> createCommonResourceInfo(CommonResourceInfoType value) {
        return new JAXBElement<CommonResourceInfoType>(_CommonResourceInfo_QNAME, CommonResourceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndValueStringListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "nvsList")
    public JAXBElement<NameAndValueStringListType> createNvsList(NameAndValueStringListType value) {
        return new JAXBElement<NameAndValueStringListType>(_NvsList_QNAME, NameAndValueStringListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleMeObjectsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getAllManagedElementsWrtOsResponse")
    public JAXBElement<MultipleMeObjectsResponseType> createGetAllManagedElementsWrtOsResponse(MultipleMeObjectsResponseType value) {
        return new JAXBElement<MultipleMeObjectsResponseType>(_GetAllManagedElementsWrtOsResponse_QNAME, MultipleMeObjectsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonObjectInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "commonObjectInfo")
    public JAXBElement<CommonObjectInfoType> createCommonObjectInfo(CommonObjectInfoType value) {
        return new JAXBElement<CommonObjectInfoType>(_CommonObjectInfo_QNAME, CommonObjectInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "capacityExceeded")
    public JAXBElement<BaseExceptionMessageType> createCapacityExceeded(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_CapacityExceeded_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "objectInUse")
    public JAXBElement<BaseExceptionMessageType> createObjectInUse(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_ObjectInUse_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllDataIteratorRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getManagedElementsIteratorRequest")
    public JAXBElement<GetAllDataIteratorRequestType> createGetManagedElementsIteratorRequest(GetAllDataIteratorRequestType value) {
        return new JAXBElement<GetAllDataIteratorRequestType>(_GetManagedElementsIteratorRequest_QNAME, GetAllDataIteratorRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleMeObjectsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getManagedElementsIteratorResponse")
    public JAXBElement<MultipleMeObjectsResponseType> createGetManagedElementsIteratorResponse(MultipleMeObjectsResponseType value) {
        return new JAXBElement<MultipleMeObjectsResponseType>(_GetManagedElementsIteratorResponse_QNAME, MultipleMeObjectsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayerRateListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/lay/v1", name = "layerRateListType")
    public JAXBElement<LayerRateListType> createLayerRateListType(LayerRateListType value) {
        return new JAXBElement<LayerRateListType>(_LayerRateListType_QNAME, LayerRateListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "protectionEffortNotMet")
    public JAXBElement<BaseExceptionMessageType> createProtectionEffortNotMet(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_ProtectionEffortNotMet_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedPackingFormat")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedPackingFormat(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedPackingFormat_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "me")
    public JAXBElement<ManagedElementType> createMe(ManagedElementType value) {
        return new JAXBElement<ManagedElementType>(_Me_QNAME, ManagedElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "commLoss")
    public JAXBElement<BaseExceptionMessageType> createCommLoss(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_CommLoss_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "invalidFilterDefinition")
    public JAXBElement<BaseExceptionMessageType> createInvalidFilterDefinition(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InvalidFilterDefinition_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndAnyValueListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "nvList")
    public JAXBElement<NameAndAnyValueListType> createNvList(NameAndAnyValueListType value) {
        return new JAXBElement<NameAndAnyValueListType>(_NvList_QNAME, NameAndAnyValueListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "internalError")
    public JAXBElement<BaseExceptionMessageType> createInternalError(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_InternalError_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "notInValidState")
    public JAXBElement<BaseExceptionMessageType> createNotInValidState(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_NotInValidState_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultipleMeObjectsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/mri/xsd/mer/v1", name = "getAllManagedElementsPassingFilterResponse")
    public JAXBElement<MultipleMeObjectsResponseType> createGetAllManagedElementsPassingFilterResponse(MultipleMeObjectsResponseType value) {
        return new JAXBElement<MultipleMeObjectsResponseType>(_GetAllManagedElementsPassingFilterResponse_QNAME, MultipleMeObjectsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "unsupportedRoutingConstraints")
    public JAXBElement<BaseExceptionMessageType> createUnsupportedRoutingConstraints(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_UnsupportedRoutingConstraints_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseExceptionMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/msg/v1", name = "entityNotFound")
    public JAXBElement<BaseExceptionMessageType> createEntityNotFound(BaseExceptionMessageType value) {
        return new JAXBElement<BaseExceptionMessageType>(_EntityNotFound_QNAME, BaseExceptionMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceStateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1", name = "resourceState", scope = CommonResourceInfoType.class)
    public JAXBElement<ResourceStateType> createCommonResourceInfoTypeResourceState(ResourceStateType value) {
        return new JAXBElement<ResourceStateType>(_CommonResourceInfoTypeResourceState_QNAME, ResourceStateType.class, CommonResourceInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1", name = "networkAccessDomain", scope = CommonResourceInfoType.class)
    public JAXBElement<String> createCommonResourceInfoTypeNetworkAccessDomain(String value) {
        return new JAXBElement<String>(_CommonResourceInfoTypeNetworkAccessDomain_QNAME, String.class, CommonResourceInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiEventInventoryAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1", name = "meiAttributes", scope = CommonResourceInfoType.class)
    public JAXBElement<MultiEventInventoryAttributesType> createCommonResourceInfoTypeMeiAttributes(MultiEventInventoryAttributesType value) {
        return new JAXBElement<MultiEventInventoryAttributesType>(_CommonResourceInfoTypeMeiAttributes_QNAME, MultiEventInventoryAttributesType.class, CommonResourceInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrb/xsd/cri/v1", name = "source", scope = CommonResourceInfoType.class)
    public JAXBElement<SourceType> createCommonResourceInfoTypeSource(SourceType value) {
        return new JAXBElement<SourceType>(_CommonResourceInfoTypeSource_QNAME, SourceType.class, CommonResourceInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "namingOs", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeNamingOs(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeNamingOs_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "userLabel", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeUserLabel(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeUserLabel_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AliasNameListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "aliasNameList", scope = CommonObjectInfoType.class)
    public JAXBElement<AliasNameListType> createCommonObjectInfoTypeAliasNameList(AliasNameListType value) {
        return new JAXBElement<AliasNameListType>(_CommonObjectInfoTypeAliasNameList_QNAME, AliasNameListType.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "owner", scope = CommonObjectInfoType.class)
    public JAXBElement<String> createCommonObjectInfoTypeOwner(String value) {
        return new JAXBElement<String>(_CommonObjectInfoTypeOwner_QNAME, String.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "name", scope = CommonObjectInfoType.class)
    public JAXBElement<NamingAttributeType> createCommonObjectInfoTypeName(NamingAttributeType value) {
        return new JAXBElement<NamingAttributeType>(_CommonObjectInfoTypeName_QNAME, NamingAttributeType.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/coi/v1", name = "vendorExtensions", scope = CommonObjectInfoType.class)
    public JAXBElement<AnyListType> createCommonObjectInfoTypeVendorExtensions(AnyListType value) {
        return new JAXBElement<AnyListType>(_CommonObjectInfoTypeVendorExtensions_QNAME, AnyListType.class, CommonObjectInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/fmw/xsd/gen/v1", name = "neTime", scope = MultiEventInventoryAttributesType.class)
    public JAXBElement<XMLGregorianCalendar> createMultiEventInventoryAttributesTypeNeTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MultiEventInventoryAttributesTypeNeTime_QNAME, XMLGregorianCalendar.class, MultiEventInventoryAttributesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "location", scope = ManagedElementType.class)
    public JAXBElement<String> createManagedElementTypeLocation(String value) {
        return new JAXBElement<String>(_ManagedElementTypeLocation_QNAME, String.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "manufacturer", scope = ManagedElementType.class)
    public JAXBElement<String> createManagedElementTypeManufacturer(String value) {
        return new JAXBElement<String>(_ManagedElementTypeManufacturer_QNAME, String.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayerRateListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "supportedConnectionLayerRateList", scope = ManagedElementType.class)
    public JAXBElement<LayerRateListType> createManagedElementTypeSupportedConnectionLayerRateList(LayerRateListType value) {
        return new JAXBElement<LayerRateListType>(_ManagedElementTypeSupportedConnectionLayerRateList_QNAME, LayerRateListType.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamingAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "asapRef", scope = ManagedElementType.class)
    public JAXBElement<NamingAttributeType> createManagedElementTypeAsapRef(NamingAttributeType value) {
        return new JAXBElement<NamingAttributeType>(_ManagedElementTypeAsapRef_QNAME, NamingAttributeType.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationStateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "communicationState", scope = ManagedElementType.class)
    public JAXBElement<CommunicationStateType> createManagedElementTypeCommunicationState(CommunicationStateType value) {
        return new JAXBElement<CommunicationStateType>(_ManagedElementTypeCommunicationState_QNAME, CommunicationStateType.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "productName", scope = ManagedElementType.class)
    public JAXBElement<String> createManagedElementTypeProductName(String value) {
        return new JAXBElement<String>(_ManagedElementTypeProductName_QNAME, String.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "isInSyncState", scope = ManagedElementType.class)
    public JAXBElement<Boolean> createManagedElementTypeIsInSyncState(Boolean value) {
        return new JAXBElement<Boolean>(_ManagedElementTypeIsInSyncState_QNAME, Boolean.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "manufactureDate", scope = ManagedElementType.class)
    public JAXBElement<XMLGregorianCalendar> createManagedElementTypeManufactureDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ManagedElementTypeManufactureDate_QNAME, XMLGregorianCalendar.class, ManagedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tmforum.org/mtop/nrf/xsd/me/v1", name = "softwareVersion", scope = ManagedElementType.class)
    public JAXBElement<String> createManagedElementTypeSoftwareVersion(String value) {
        return new JAXBElement<String>(_ManagedElementTypeSoftwareVersion_QNAME, String.class, ManagedElementType.class, value);
    }

}
