//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 02:40:57 PM IST 
//


package com.lte.discovery.reconciliation.managed.element;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * State parameter from ITU-T state or status
 * 
 * <p>Java class for X721.StateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="X721.StateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="X721.OperationalState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.OperationalStateType" minOccurs="0"/>
 *         &lt;element name="X721.AdministrativeState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.AdministrativeStateType" minOccurs="0"/>
 *         &lt;element name="X721.UsageState" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.UsageStateType" minOccurs="0"/>
 *         &lt;element name="X721.AvailabilityStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.AvailabilityStatusType" minOccurs="0"/>
 *         &lt;element name="X721.ControlStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.ControlStatusType" minOccurs="0"/>
 *         &lt;element name="M3100.HolderStatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}M3100.HolderStatusType" minOccurs="0"/>
 *         &lt;element name="X721.Unkownstatus" type="{http://www.tmforum.org/mtop/nrb/xsd/itu/v1}X721.UnkownstatusType" minOccurs="0"/>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X721.StateType", namespace = "http://www.tmforum.org/mtop/nrb/xsd/itu/v1", propOrder = {
    "x721OperationalState",
    "x721AdministrativeState",
    "x721UsageState",
    "x721AvailabilityStatus",
    "x721ControlStatus",
    "m3100HolderStatus",
    "x721Unkownstatus",
    "any"
})
public class X721StateType {

    @XmlElement(name = "X721.OperationalState")
    protected X721OperationalStateType x721OperationalState;
    @XmlElement(name = "X721.AdministrativeState")
    protected X721AdministrativeStateType x721AdministrativeState;
    @XmlElement(name = "X721.UsageState")
    protected X721UsageStateType x721UsageState;
    @XmlElement(name = "X721.AvailabilityStatus")
    protected String x721AvailabilityStatus;
    @XmlElement(name = "X721.ControlStatus")
    protected String x721ControlStatus;
    @XmlElement(name = "M3100.HolderStatus")
    protected M3100HolderStatusType m3100HolderStatus;
    @XmlElement(name = "X721.Unkownstatus")
    protected Boolean x721Unkownstatus;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the x721OperationalState property.
     * 
     * @return
     *     possible object is
     *     {@link X721OperationalStateType }
     *     
     */
    public X721OperationalStateType getX721OperationalState() {
        return x721OperationalState;
    }

    /**
     * Sets the value of the x721OperationalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721OperationalStateType }
     *     
     */
    public void setX721OperationalState(X721OperationalStateType value) {
        this.x721OperationalState = value;
    }

    /**
     * Gets the value of the x721AdministrativeState property.
     * 
     * @return
     *     possible object is
     *     {@link X721AdministrativeStateType }
     *     
     */
    public X721AdministrativeStateType getX721AdministrativeState() {
        return x721AdministrativeState;
    }

    /**
     * Sets the value of the x721AdministrativeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721AdministrativeStateType }
     *     
     */
    public void setX721AdministrativeState(X721AdministrativeStateType value) {
        this.x721AdministrativeState = value;
    }

    /**
     * Gets the value of the x721UsageState property.
     * 
     * @return
     *     possible object is
     *     {@link X721UsageStateType }
     *     
     */
    public X721UsageStateType getX721UsageState() {
        return x721UsageState;
    }

    /**
     * Sets the value of the x721UsageState property.
     * 
     * @param value
     *     allowed object is
     *     {@link X721UsageStateType }
     *     
     */
    public void setX721UsageState(X721UsageStateType value) {
        this.x721UsageState = value;
    }

    /**
     * Gets the value of the x721AvailabilityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX721AvailabilityStatus() {
        return x721AvailabilityStatus;
    }

    /**
     * Sets the value of the x721AvailabilityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX721AvailabilityStatus(String value) {
        this.x721AvailabilityStatus = value;
    }

    /**
     * Gets the value of the x721ControlStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX721ControlStatus() {
        return x721ControlStatus;
    }

    /**
     * Sets the value of the x721ControlStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX721ControlStatus(String value) {
        this.x721ControlStatus = value;
    }

    /**
     * Gets the value of the m3100HolderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link M3100HolderStatusType }
     *     
     */
    public M3100HolderStatusType getM3100HolderStatus() {
        return m3100HolderStatus;
    }

    /**
     * Sets the value of the m3100HolderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link M3100HolderStatusType }
     *     
     */
    public void setM3100HolderStatus(M3100HolderStatusType value) {
        this.m3100HolderStatus = value;
    }

    /**
     * Gets the value of the x721Unkownstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isX721Unkownstatus() {
        return x721Unkownstatus;
    }

    /**
     * Sets the value of the x721Unkownstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setX721Unkownstatus(Boolean value) {
        this.x721Unkownstatus = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
